name: Deploy my project
on:
  push:
    branches: [ "main" , "lambda-function-setup" ]
    
  workflow_dispatch:
jobs:
 deploy-infrastructure:
    runs-on: ubuntu-latest
    env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_REGION: eu-central-1    
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      # Create bucket because of the sandbox 
      - name: Setup Terraform state bucket
        run: |
          cd infrastructure
          sh setup_s3_terraform_bucket.sh
      - name: Build source code
        run: |
          cd src
          sh build_code.sh
      - name: Deploy with terraform
        run: |
          cd infrastructure
          terraform init
          terraform apply -auto-approve
          
